# Generated by Django 4.1.3 on 2022-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
