# Generated by Django 4.1.3 on 2022-11-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img',
            field=models.FilePathField(default=1, path='d/it/img/'),
            preserve_default=False,
        ),
    ]
