# Generated by Django 4.1.3 on 2022-11-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_phone_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='img',
        ),
    ]
