# Generated by Django 4.1.3 on 2022-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_phone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.FileField(upload_to='category/static/img_category'),
        ),
    ]
