# Generated by Django 4.1.3 on 2022-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_alter_phone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.FileField(upload_to='static/img_category/'),
        ),
    ]
