# Generated by Django 4.1.3 on 2022-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_alter_screensize_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to='img_category/'),
        ),
    ]
